package com.gxwz.medical.entity;

import java.util.Date;

public class Mbbill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mbbill.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mbbill.cordno
     *
     * @mbggenerated
     */
    private String cordno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mbbill.persname
     *
     * @mbggenerated
     */
    private String persname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mbbill.illname
     *
     * @mbggenerated
     */
    private String illname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mbbill.startday
     *
     * @mbggenerated
     */
    private Date startday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mbbill.id
     *
     * @return the value of t_mbbill.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mbbill.id
     *
     * @param id the value for t_mbbill.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mbbill.cordno
     *
     * @return the value of t_mbbill.cordno
     *
     * @mbggenerated
     */
    public String getCordno() {
        return cordno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mbbill.cordno
     *
     * @param cordno the value for t_mbbill.cordno
     *
     * @mbggenerated
     */
    public void setCordno(String cordno) {
        this.cordno = cordno == null ? null : cordno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mbbill.persname
     *
     * @return the value of t_mbbill.persname
     *
     * @mbggenerated
     */
    public String getPersname() {
        return persname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mbbill.persname
     *
     * @param persname the value for t_mbbill.persname
     *
     * @mbggenerated
     */
    public void setPersname(String persname) {
        this.persname = persname == null ? null : persname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mbbill.illname
     *
     * @return the value of t_mbbill.illname
     *
     * @mbggenerated
     */
    public String getIllname() {
        return illname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mbbill.illname
     *
     * @param illname the value for t_mbbill.illname
     *
     * @mbggenerated
     */
    public void setIllname(String illname) {
        this.illname = illname == null ? null : illname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mbbill.startday
     *
     * @return the value of t_mbbill.startday
     *
     * @mbggenerated
     */
    public Date getStartday() {
        return startday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mbbill.startday
     *
     * @param startday the value for t_mbbill.startday
     *
     * @mbggenerated
     */
    public void setStartday(Date startday) {
        this.startday = startday;
    }
}