package com.gxwz.medical.entity;

public class Point {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point.pointno
     *
     * @mbggenerated
     */
    private String pointno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point.agencyno
     *
     * @mbggenerated
     */
    private String agencyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point.agencyname
     *
     * @mbggenerated
     */
    private String agencyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point.pointname
     *
     * @mbggenerated
     */
    private String pointname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_point.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point.id
     *
     * @return the value of t_point.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point.id
     *
     * @param id the value for t_point.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point.pointno
     *
     * @return the value of t_point.pointno
     *
     * @mbggenerated
     */
    public String getPointno() {
        return pointno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point.pointno
     *
     * @param pointno the value for t_point.pointno
     *
     * @mbggenerated
     */
    public void setPointno(String pointno) {
        this.pointno = pointno == null ? null : pointno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point.agencyno
     *
     * @return the value of t_point.agencyno
     *
     * @mbggenerated
     */
    public String getAgencyno() {
        return agencyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point.agencyno
     *
     * @param agencyno the value for t_point.agencyno
     *
     * @mbggenerated
     */
    public void setAgencyno(String agencyno) {
        this.agencyno = agencyno == null ? null : agencyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point.agencyname
     *
     * @return the value of t_point.agencyname
     *
     * @mbggenerated
     */
    public String getAgencyname() {
        return agencyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point.agencyname
     *
     * @param agencyname the value for t_point.agencyname
     *
     * @mbggenerated
     */
    public void setAgencyname(String agencyname) {
        this.agencyname = agencyname == null ? null : agencyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point.pointname
     *
     * @return the value of t_point.pointname
     *
     * @mbggenerated
     */
    public String getPointname() {
        return pointname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point.pointname
     *
     * @param pointname the value for t_point.pointname
     *
     * @mbggenerated
     */
    public void setPointname(String pointname) {
        this.pointname = pointname == null ? null : pointname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_point.level
     *
     * @return the value of t_point.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_point.level
     *
     * @param level the value for t_point.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}