package com.gxwz.medical.entity;

public class Zcpolicy {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zcpolicy.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zcpolicy.runyear
     *
     * @mbggenerated
     */
    private Integer runyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zcpolicy.rate
     *
     * @mbggenerated
     */
    private Long rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zcpolicy.maxline
     *
     * @mbggenerated
     */
    private Long maxline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_zcpolicy.runrate
     *
     * @mbggenerated
     */
    private Long runrate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zcpolicy.id
     *
     * @return the value of t_zcpolicy.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zcpolicy.id
     *
     * @param id the value for t_zcpolicy.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zcpolicy.runyear
     *
     * @return the value of t_zcpolicy.runyear
     *
     * @mbggenerated
     */
    public Integer getRunyear() {
        return runyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zcpolicy.runyear
     *
     * @param runyear the value for t_zcpolicy.runyear
     *
     * @mbggenerated
     */
    public void setRunyear(Integer runyear) {
        this.runyear = runyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zcpolicy.rate
     *
     * @return the value of t_zcpolicy.rate
     *
     * @mbggenerated
     */
    public Long getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zcpolicy.rate
     *
     * @param rate the value for t_zcpolicy.rate
     *
     * @mbggenerated
     */
    public void setRate(Long rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zcpolicy.maxline
     *
     * @return the value of t_zcpolicy.maxline
     *
     * @mbggenerated
     */
    public Long getMaxline() {
        return maxline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zcpolicy.maxline
     *
     * @param maxline the value for t_zcpolicy.maxline
     *
     * @mbggenerated
     */
    public void setMaxline(Long maxline) {
        this.maxline = maxline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zcpolicy.runrate
     *
     * @return the value of t_zcpolicy.runrate
     *
     * @mbggenerated
     */
    public Long getRunrate() {
        return runrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zcpolicy.runrate
     *
     * @param runrate the value for t_zcpolicy.runrate
     *
     * @mbggenerated
     */
    public void setRunrate(Long runrate) {
        this.runrate = runrate;
    }
}